In [1]:
import numpy as np

In [2]:
# Write a function so that the columns of the output matrix are powers of the input
# vector.

In [3]:
arr=np.random.randn(3,4)
arr

array([[ 1.50100956, -0.73826856,  0.01820163,  2.39852035],
       [ 0.30588775,  1.46383613,  1.59610881, -0.58768125],
       [-0.49113335,  0.01703194, -0.4706581 ,  0.29384798]])

In [4]:
pow(arr,3)

array([[ 3.38181915e+00, -4.02386238e-01,  6.03018667e-06,
         1.37984474e+01],
       [ 2.86210950e-02,  3.13673179e+00,  4.06618830e+00,
        -2.02967038e-01],
       [-1.18467238e-01,  4.94074023e-06, -1.04259731e-01,
         2.53727840e-02]])

In [5]:
# Question: Write a function to find moving average in an array over a window:
# Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [6]:
lst = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
arr_1 = np.array(lst)
arr_1

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [7]:
# here k = 3
# Thus, the moving average sequence has n-k+1=10-3+1=7
print('y1     {:.3f}'.format((3+5+7)/3))
print('y2     {:.3f}'.format((5+7+2)/3))
print('y3     {:.3f}'.format((7+2+8)/3))
print('y4     {:.3f}'.format((2+8+10)/3))
print('y5     {:.3f}'.format((8+10+11)/3))
print('y6     {:.3f}'.format((10+11+65)/3))
print('y7     {:.3f}'.format((11+65+72)/3))
print('y8     {:.3f}'.format((65+72+81)/3))
print('y9     {:.3f}'.format((72+81+99)/3))
print('y10     {:.3f}'.format((81+99+100)/3))
print('y11     {:.3f}'.format((99+100+150)/3))

y1     5.000
y2     4.667
y3     5.667
y4     6.667
y5     9.667
y6     28.667
y7     49.333
y8     72.667
y9     84.000
y10     93.333
y11     116.333
